# Generated by Django 4.1.5 on 2023-01-26 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_create",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 26, 14, 2, 24, 163520, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_edited",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 26, 14, 2, 24, 163520, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
